# Generated by Django 3.1.3 on 2023-05-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230519_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='glasses',
            name='code',
            field=models.CharField(default='0000', editable=False, max_length=255, unique=True),
        ),
    ]
