# Generated by Django 3.1.3 on 2023-05-19 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_glasses_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='discount',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
