# Generated by Django 3.1.3 on 2023-09-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('store', '0005_auto_20230519_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glasses',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='glasses',
            name='cart',
            field=models.ManyToManyField(blank=True, default=None, related_name='cart', to='profiles.Customer'),
        ),
    ]
