# Generated by Django 3.1.3 on 2023-09-14 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('store', '0006_auto_20230913_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('specification', models.TextField()),
                ('image1', models.ImageField(upload_to='gallary', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('image2', models.ImageField(blank=True, upload_to='gallary', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('code', models.CharField(default='0000', editable=False, max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ManyToManyField(blank=True, default=None, related_name='cart2', to='profiles.Customer')),
                ('category', models.ManyToManyField(default=None, related_name='catagory2', to='store.Category')),
                ('liked', models.ManyToManyField(blank=True, default=None, related_name='likes2', to='profiles.Customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
