# Generated by Django 3.1.3 on 2023-09-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_glasses2'),
    ]

    operations = [
        migrations.AddField(
            model_name='glasses',
            name='productStatus',
            field=models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20),
        ),
    ]
